### ISSUE TITLE
Fetching CB 0.8.1

### ISSUE THREAD

**Issue by derekchiang** [cstar/heroku-buildpack-chicagoboss#1]
Hello,

According to my Heroku log, the build stack fetches CB 0.8.1, rather than 0.8.5.

Best,
Derek

**Comment by derekchiang** [comment]
Now it just plainly doesn't work...

Log after "git push heroku master":

Counting objects: 121, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (115/115), done.
Writing objects: 100% (121/121), 277.79 KiB, done.
Total 121 (delta 51), reused 0 (delta 0)
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> ChicagoBoss app detected
remote: -----> Using Erlang/OTP OTP_R15B03-1
remote: -------> Fetching Erlang/OTP OTP_R15B03-1
remote: -------> Unpacking Erlang/OTP OTP_R15B03-1
remote: -------> Installing Erlang/OTP OTP_R15B03-1
remote: 
remote: -----> Using ChicagoBoss v0.8.5
remote: -----> Not in cache, fetching from https://nodeload.github.com/evanmiller/ChicagoBoss/tar.gz/v0.8.5
remote: -------> Fetching ChicagoBoss v0.8.5
remote: -------> Unpacking ChicagoBoss v0.8.5
remote: 
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Exiting with failure status due to previous errors
remote:  !     Heroku push rejected, failed to compile Chicagoboss app
remote: 
To git@heroku.com:infinite-earth-5399.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:infinite-earth-5399.git'

**Comment by cstar** [comment]
Ah, yes, apologies.
The CB repo does not have tags for 0.8.5, so we can't get it with the current approach for this build pack.
