### ISSUE TITLE
error creating heroku app

### ISSUE THREAD

**Issue by mithereal** [cstar/heroku-buildpack-chicagoboss#5]
my instance of heroku doesnt have rsync installed so i changed it here https://github.com/mithereal/heroku-buildpack-chicagoboss and erlang installs correctly, but im having issues with running cb as the deps dir just symlinks to /app/tmp/cache/deps which nothing exists at, seems why its failing any ideas on howto fix?

**Comment by cstar** [comment]
Weird you don't have rsync installed and that error crept through.

Apparently we are not alone: https://github.com/dbrgn/heroku-buildpack-python-sklearn/issues/2

I'll change the rsync lines to some cp -a.

Thank you for the report
